enableVersioning: true
handle: caseStudy
name: 'Case Study'
propagationMethod: all
siteSettings:
  8bd7e41f-a4b4-4a7b-a64b-e17c241cb21a:
    enabledByDefault: true
    hasUrls: true
    template: templates/case-study
    uriFormat: 'case-studies/{slug}'
type: channel
