enableVersioning: true
handle: solutions
name: Solutions
propagationMethod: all
siteSettings:
  8bd7e41f-a4b4-4a7b-a64b-e17c241cb21a:
    enabledByDefault: true
    hasUrls: true
    template: templates/solutions
    uriFormat: solutions
type: single
