contentColumnType: text
fieldGroup: d66444ad-ced1-4ef4-a82a-c13bd813737d
handle: address
instructions: ''
name: Address
searchable: true
settings:
  addRowLabel: 'Add a row'
  columnType: text
  columns:
    __assoc__:
      -
        - col1
        -
          __assoc__:
            -
              - heading
              - Address
            -
              - handle
              - address
            -
              - width
              - ''
            -
              - type
              - multiline
      -
        - col2
        -
          __assoc__:
            -
              - heading
              - 'Google Maps Link'
            -
              - handle
              - googleMapsLink
            -
              - width
              - ''
            -
              - type
              - url
  defaults:
    -
      __assoc__:
        -
          - col1
          - ''
        -
          - col2
          - ''
  maxRows: '1'
  minRows: '1'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Table
