contentColumnType: text
fieldGroup: 1545bc45-0318-4f91-aadb-295ecf175197
handle: blogPosrExceprt
instructions: ''
name: 'Blog Posr Exceprt'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '2'
  multiline: '1'
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
