contentColumnType: text
fieldGroup: c4089029-5045-435d-9c59-e9f595dc023e
handle: caseStudyHeader
instructions: ''
name: 'Case Study Header'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
