contentColumnType: string
fieldGroup: d66444ad-ced1-4ef4-a82a-c13bd813737d
handle: email
instructions: ''
name: Email
searchable: true
settings:
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Email
