contentColumnType: text
fieldGroup: 46112973-481b-41f4-b153-4e91c59e2d19
handle: firstSectionSubheader
instructions: 'Blue text below gray header'
name: 'First Section Subheader'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
