contentColumnType: text
fieldGroup: 46112973-481b-41f4-b153-4e91c59e2d19
handle: homeTestimonials
instructions: ''
name: Testimonials
searchable: true
settings:
  addRowLabel: 'Add a testimonial'
  columnType: text
  columns:
    __assoc__:
      -
        - col1
        -
          __assoc__:
            -
              - heading
              - Testimonial
            -
              - handle
              - testimonial
            -
              - width
              - ''
            -
              - type
              - multiline
  defaults:
    -
      __assoc__:
        -
          - col1
          - ''
  maxRows: ''
  minRows: '1'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Table
