fieldLayouts:
  3c883d92-2723-41f4-bcb1-34c04dec74d0:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            autofocus: false
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 87185b1d-e364-4808-9db2-10d723b3be5c
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: df6f9a72-677f-4697-b728-702d2b1d488d
            instructions: 'This exceprts appears on the blog landing page'
            label: ''
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 5e5d1de9-54fb-4fb9-bc2f-df3bb9b78fe0
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 7d28d61b-835c-4acd-b754-4fa4789a70e0
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Blog Article'
        sortOrder: 1
handle: blogArticle
hasTitleField: true
name: 'Blog Article'
section: 771737f8-a28c-4ff7-a6b9-7302ba424b1c
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
