fieldLayouts:
  1ab2aace-585d-4284-9c5d-151029fa9d7b:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            autofocus: false
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: f25020e2-0b2e-4522-a23a-1b69cb2fcfd1
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: feba505b-7782-4ba9-ad81-4067891569ad
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: be8ade1e-3182-40b8-9bb1-b7b0d6ba3f41
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: d312722c-472f-40d2-aa8f-d8ba26fd1991
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: f5f54b99-adcf-4624-b3bd-0644ed8b3b48
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Case Studies Landing'
        sortOrder: 1
      -
        elements:
          -
            fieldUid: fbd4a428-fcfa-4d20-9916-8aa72c45fc9f
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: SEO
        sortOrder: 2
handle: caseStudiesLanding
hasTitleField: false
name: 'Case Studies Landing'
section: 3e4a927d-56bd-4241-813b-7f4c16a01b93
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
