fieldLayouts:
  d9466523-bbdf-4ca2-a941-cdb9ca24e999:
    tabs:
      -
        elements:
          -
            instructions: null
            label: ''
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: f25020e2-0b2e-4522-a23a-1b69cb2fcfd1
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: feba505b-7782-4ba9-ad81-4067891569ad
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 3586359e-a0e4-415f-a9db-e0423af66d41
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: bd38238e-edf9-4565-acb7-23b607eff3b9
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 53651d11-5fc5-49a0-b0c0-0fa60e3d42d6
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: c3accd9e-e693-40ac-94c1-d2ab439fb08f
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 20d5f173-f5b8-4086-ad45-368ea3f06c73
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Solutions
        sortOrder: 1
handle: solutions
hasTitleField: false
name: Solutions
section: 8a5fa007-4d23-4e01-b7b0-fc4e420f7b09
sortOrder: 1
titleFormat: '{section.name|raw}'
